name: Update Episodes JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Grant write permission to the repository

jobs:
  update-episodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate episodes.json
        run: |
          echo "{" > episodes.json
          echo '  "episodes": [' >> episodes.json

          first_entry=true
          for file in $(ls -t episodes/*.mp3); do
            filename=$(basename "$file")
            
            # Extract title from filename: Remove leading number, replace dashes with spaces
            title=$(echo "$filename" | sed -E 's/^[0-9]+-//; s/-/ /g; s/.mp3//')

            # Add comma for JSON formatting except for the first entry
            if [ "$first_entry" = false ]; then
              echo "," >> episodes.json
            else
              first_entry=false
            fi

            echo "    {\"title\": \"$title\", \"file\": \"$filename\"}" >> episodes.json
          done

          echo "  ]" >> episodes.json
          echo "}" >> episodes.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add episodes.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update episodes.json"
          git push
